version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd backend_test
      - echo Installing NPM dependencies...
      - npm ci --production
  build:
    commands:
      - echo Build started on `date`
      - echo Build completed on `date`
artifacts:
  base-directory: backend_test
  files:
    - '**/*'
